server:
  port: 8001
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka

 
spring:     
  application:
    name: Inpy_Common
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      uri: http://localhost:8888


logging:
  file:
    name: D:\microservices\logs\InpyLogs.log


management:
  endpoints:
    web:
      exposure:
        include: "*"
